pipeline {
	agent any
	stages{
		stage('Build'){
			steps {
				echo "Build"
			}
		}
				stage('Test'){
			steps {
				echo "Test"
			}
		}
		stage('Integreation Test'){
			steps {
				echo "Integreation Test"
			}
		}

	}

}
