pipeline {
	agent { docker { image 'maven:3.6.3'}}
	stages{
		stage('Build'){
			steps {
				sh 'mvn --version'
				echo "Build"
			}
		}
				stage('Test'){
			steps {
				echo "Test"
			}
		}
		stage('Integreation Test'){
			steps {
				echo "Integreation Test"
			}
		}

	}
	
	post {
		always{
			echo 'I run always'
		}
		success{
			echo 'I run on success'
		}
		failure{
			echo 'I run on failure'
		}
		//changed
	}

}
