pipeline {
	agent any
	stages{
		stage('Build'){
			steps {
				echo "Build"
			}
		}
				stage('Test'){
			steps {
				echo "Test"
			}
		}
		stage('Integreation Test'){
			steps {
				echo "Integreation Test"
			}
		}

	}post {
		always{
			echo 'I run always'
		}
		success{
			echo 'I run on success'
		}
		failure{
			echo 'I run on failure'
		}
	}

}
